### ISSUE TITLE
Set up Firebase core and configuration in Flutter

### ISSUE THREAD

**Issue by mina24nagy** [mina24nagy/NougaHub#3]
### 🎯 Objective
Initialize Firebase in the Flutter app and confirm successful setup on launch.

### 🛠 Steps
1. Add dependencies in `pubspec.yaml`:
```yaml
dependencies:
  firebase_core: ^latest
  firebase_auth: ^latest
```

2. Update `main.dart`:
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}
```

### ✅ Acceptance Criteria
- Firebase initializes without errors.
- App launches with Firebase configured correctly.
